[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
identifier = "services"
name = "Services"
url = "#"
weight = 20

[[main]]
name = "About Me"
url = "/About-Me/"
weight = 40

[[main]]
name = "Contact"
url = "/#contact"
weight = 80

[[footer]]
identifier = "website"
name = "Company"
url = "#"
weight = 10

[[footer]]
parent = "website"
name = "Home"
url = "/"
weight = 10

[[footer]]
parent = "website"
name = "Services"
url = "/consulting/"
weight = 20

[[footer]]
parent = "website"
name = "Contact"
url = "/#contact"
weight = 30

[[footer]]
identifier = "hosting"
name = "Resources"
url = "#"
weight = 20

[[footer]]
parent = "hosting"
name = "Blog"
url = "/blog/"
weight = 10

[[services]]
name = "Consulting"
url = "/consulting/"
weight = 10
[services.params]
icon = "uil uil-chart-line"

[[services]]
name = "Development"
url = "/#development"
weight = 20
[services.params]
icon = "uil uil-desktop"

[[services]]
name = "Training"
url = "/#training"
weight = 30
[services.params]
icon = "uil uil-graduation-cap"